export const articlesMock = {
  status: 'ok',
  total_hits: 1153,
  page: 1,
  total_pages: 24,
  page_size: 50,
  articles: [
    {
      title: 'Steve Jobs Biography Author to Write Elon Musk Story',
      author:
        'Entrepreneur Entrepreneur Empowering People in the Business of Changing the World | Entrepreneur® is dedicated to fueling the world’s visionary leaders compelled to make a difference through their innovative ideas, businesses, and points of view. View profile',
      published_date: '2021-08-08 21:45:00',
      published_date_precision: 'timezone unknown',
      link: 'https://www.theepochtimes.com/steve-jobs-biography-author-to-write-elon-musk-story_3935598.html',
      clean_url: 'theepochtimes.com',
      excerpt:
        'By Entrepreneur Staff Walter Isaacson, the American author who wrote the bestselling biography of Apple co-founder Steve Jobs, will work on ...',
      summary:
        "Elon Musk, founder and CEO of SpaceX, participates in a press conference at the Kennedy Space Center in Cape Canaveral, Fla., on May 27, 2020. (Saul Martinez/Getty Images)\n\nSteve Jobs Biography Author to Write Elon Musk Story\n\nMusk noted that the writer accompanied him for several days to gather material for the book\n\nWalter Isaacson, the American author who wrote the bestselling biography of Apple co-founder Steve Jobs, will work on the life story of Tesla and SpaceX president Elon Musk.\n\n'If y",
      rights: 'theepochtimes.com',
      rank: 1778,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['EntMagazine'],
      media: 'https://img.theepochtimes.com/assets/uploads/2021/02/20/Elon-Musk-1200x800.jpg',
      is_opinion: false,
      twitter_account: '@entrepreneur',
      _score: 24.350666,
      _id: '81fad140ea9884bf374bb306a2ac27a3',
    },
    {
      title: 'Fact check: Elon Musk did not offer to buy and delete Facebook',
      author: 'McKenzie Sadeghi',
      published_date: '2021-08-06 17:38:38',
      published_date_precision: 'full',
      link: 'https://www.usatoday.com/story/news/factcheck/2021/08/06/fact-check-claim-elon-musk-and-facebook-originated-satire/5497094001/',
      clean_url: 'usatoday.com',
      excerpt:
        'A 2018 satirical article about billionaire Elon Musk and Facebook has turned into false claims on social media.',
      summary:
        "Elon Musk's brain-implant ‘Neuralink' could test in people soonAfter sharing a video of a monkey playing video games with its mind, Elon Musk is ready to put a chip in your brain.Since 2016, when a SpaceX rocket exploded during a launchpad test and destroyed a Facebook satellite it was carrying, billionaires Elon Musk and Mark Zuckerberg have had an ongoing feud.Some on social media are claiming Musk, who has repeatedly criticized Facebook, offered to purchase the platform so he could permanentl",
      rights: 'usatoday.com',
      rank: 126,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Mckenzie Sadeghi'],
      media:
        'https://www.gannett-cdn.com/-mm-/d8d0774057d19139d16e6ede624d76e89947662d/c=1-0-1365-767/local/-/media/2021/06/01/USATODAY/usatsports/247WallSt.com-247WS-889342-imageForEntry1-f4R.jpg?auto=webp&format=pjpg&width=1200',
      is_opinion: false,
      twitter_account: '@usatoday',
      _score: 24.241861,
      _id: '1b8ebf86cf4909843ebffcf197536115',
    },
    {
      title: 'SpaceX briefly puts together largest rocket in history at Texas base',
      author: 'Danielle Haynes',
      published_date: '2021-08-06 18:37:11',
      published_date_precision: 'full',
      link: 'https://www.upi.com/Science_News/2021/08/06/Spacex-Starship-Super-Heavy-rocket/2161628271028',
      clean_url: 'upi.com',
      excerpt:
        "SpaceX briefly constructed the largest rocket ever made Friday, attaching the U.S. aerospace company's Starship spacecraft to the Super Heavy booster at its facility in Texas.",
      summary:
        "The SpaceX Super Heavy Booster 4 is seen at the company's Starbase in Boca Chica, Texas. Photo by SpaceX/UPI | License Photo\n\nSpaceX CEO Elon Musk shared photos on Friday of the company's Starship spacecraft stacked atop its Super Heavy Booster 4 on the launch mount at Starbase in Boca Chica, Texas, in preparation for the company's first orbital Starship launch. Photo courtesy Elon Musk/SpaceX | License Photo\n\nSpaceX CEO Elon Musk shared photos Friday of the company's Starship spacecraft stacked",
      rights: 'upi.com',
      rank: 1116,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Danielle Haynes'],
      media:
        'https://cdnph.upi.com/sv/ph/og/upi/2161628271028/2021/1/8c782bd3c773d1b1f1d0151ea406dae4/v1.5/SpaceX-briefly-puts-together-largest-rocket-in-history-at-Texas-base.jpg',
      is_opinion: false,
      twitter_account: '@UPI',
      _score: 23.744215,
      _id: '7b3f907952894cd922b104c83507e463',
    },
    {
      title: "SpaceX completes stacking Starship for 1st orbital flight. Elon Musk says it's a 'dream come true.'",
      author: null,
      published_date: '2021-08-07 15:45:00',
      published_date_precision: 'timezone unknown',
      link: 'https://www.businessinsider.com/elon-musk-spacex-completes-stacking-starship-dream-come-true-2021-8',
      clean_url: 'businessinsider.com',
      excerpt:
        "Elon Musk's SpaceX stacked a Starship prototype rocket atop a Super Heavy rocket booster for the first time on Friday.",
      summary:
        "© Hannibal Hanschke Pool / Getty Images SpaceX founder Elon Musk. Hannibal Hanschke Pool / Getty Images\n\n\nElon Musk on Friday shared photos of SpaceX's Starship atop a Super Heavy rocket booster before its first orbital flight.At about 400 feet tall, it was the biggest rocket ever constructed, BBC News reported. The construction took place at SpaceX's launch site, Starbase, in Boca Chica, Texas. Musk's photos were the latest in a series he's posted showed the spaceship being stacked together. -E",
      rights: 'msn.com',
      rank: 110,
      topic: 'science',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AAKeJZT.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg&x=2634&y=1438',
      is_opinion: false,
      twitter_account: null,
      _score: 23.667011,
      _id: '0935e4742a36f26ba86cddc7c0e2176e',
    },
    {
      title: "Elon Musk says Jeff Bezos would be on Pluto 'if lawyers & lobbying could get you to orbit'",
      author: 'Republic World',
      published_date: '2021-08-12 16:27:00',
      published_date_precision: 'full',
      link: 'https://www.republicworld.com/technology-news/science/elon-musk-says-jeff-bezos-would-be-on-pluto-if-lawyers-and-lobbying-could-get-you-to-orbit.html',
      clean_url: 'republicworld.com',
      excerpt:
        "SpaceX CEO Elon Musk took a jibe at the Blue Origin's founder, Jeff Bezos saying former would be on Pluto by now if lobbying and lawyers could get you to orbit.",
      summary:
        'Sneering and mocking a remark at Blue Origin\'s founder, Jeff Bezos, on August 12, SpaceX CEO Elon Musk said the former would be on Pluto by no if lobbying and lawyers could get you to orbit. Musk hit out at the billionaire space rival in the latest barb in a war of words. Recently, the two were kicked into overdrive when NASA awarded SpaceX a lunar lander contract over Bezos-owned space entity.  While replying to a tweet, Elon Musk wrote, "If lobbying & lawyers could get u to orbit, Bezos would ',
      rights: 'republicworld.com',
      rank: 9700,
      topic: 'science',
      country: 'US',
      language: 'en',
      authors: ['Republic World'],
      media: 'https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/evtmvzo1flrwpjdl_1628783344.jpeg',
      is_opinion: false,
      twitter_account: '@republic',
      _score: 23.43712,
      _id: '0a0581ebd9b2296f8a327bd97750f268',
    },
    {
      title: "Elon Musk's Starship rocket 'fully stacked' as it's set for space launch",
      author: 'Katie Davis',
      published_date: '2021-08-06 16:29:52',
      published_date_precision: 'full',
      link: 'https://www.the-sun.com/tech/3426346/elon-musk-starship-rocket-fully-stacked/',
      clean_url: 'the-sun.com',
      excerpt:
        "ELON Musk has revealed snaps of his Starship rocket 'full stacked' ahead of it blasting into space from Texas. The billionaire admitted on Twitter it was a 'dream come true'…",
      summary:
        "ELON Musk has revealed snaps of his Starship rocket \"full stacked\" ahead of it blasting into space from Texas.\nThe billionaire admitted on Twitter it was a \"dream come true\" to see his spacecraft fully built as SpaceX gears up for the rocket's first orbital test flight.\nElon Musk shared pictures of SpaceX's Starship 'full stacked'Credit: Twitter/Elon Musk\nThe billionaire said it is a 'dream come true' to see his rocket fully builtCredit: Twitter/Elon Musk\nMusk, CEO of the aerospace company, has ",
      rights: 'the-sun.com',
      rank: 9575,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Katie Davis'],
      media:
        'https://www.the-sun.com/wp-content/uploads/sites/6/2021/08/TT_ElonMuskOP.jpg?strip=all&quality=100&w=1200&h=800&crop=1',
      is_opinion: false,
      twitter_account: '@thesun',
      _score: 23.413008,
      _id: '2e7201c9f245e30bdd8d432437bd62c7',
    },
    {
      title: "Man shares image of auto driver 'accepting' cryptocurrency; social media users shocked",
      author: 'Fp Trending',
      published_date: '2021-08-12 13:23:38',
      published_date_precision: 'full',
      link: 'https://ca.sports.yahoo.com/news/man-shares-image-auto-driver-095448025.html?src=rss',
      clean_url: 'yahoo.com',
      excerpt: 'Cryptocurrency is not a legal tender in India but it has already created a buzz in the country',
      summary:
        'Nowadays, everyone is talking about cryptocurrency and its value. All thanks to tech billionaire Elon Musk, who has been a staunch supporter of everything crypto.\n\nEver since cryptocurrency and Bitcoin gained popularity in India, more and more youngsters have actively been involved in new ways of trading crypto.\n\nNow, a photo of an auto rickshaw driver with a paper attached to his vehicle which reads, "we accept cryptocurrency" has gone viral on social media after a Twitter user shared the photo',
      rights: 'yahoo.com',
      rank: 30,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Fp Trending'],
      media:
        'https://s.yimg.com/uu/api/res/1.2/3tYoq5df6lQs4XzutanmBA--~B/aD0yODU7dz0zODA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/firstpost_248/44d66a60b603b215ec41adad79d97de2',
      is_opinion: false,
      twitter_account: '@YahooCASports',
      _score: 23.408068,
      _id: 'f7487e69adb744756f0c82257b0176eb',
    },
    {
      title: "SpaceX completes stacking Starship for 1st orbital flight. Elon Musk says its a 'dream come true.'",
      author: 'Zahra Tayeb',
      published_date: '2021-08-07 15:20:00',
      published_date_precision: 'full',
      link: 'https://www.businessinsider.com/elon-musk-spacex-completes-stacking-starship-dream-come-true-2021-8',
      clean_url: 'businessinsider.com',
      excerpt:
        "Elon Musk's SpaceX stacked a Starship prototype rocket atop a Super Heavy rocket booster for the first time on Friday.",
      summary:
        "Elon Musk on Friday shared photos of SpaceX's Starship atop a Super Heavy rocket booster before its first orbital flight.At about 400 feet tall, it was the biggest rocket ever constructed, BBC News reported. The construction took place at SpaceX's launch site, Starbase, in Boca Chica, Texas. Musk's photos were the latest in a series he's posted showed the spaceship being stacked together. —Elon Musk (@elonmusk) August 6, 2021CNBC's Michael Sheetz asked Musk what it felt like witnessing the miles",
      rights: 'Insider',
      rank: 110,
      topic: 'business',
      country: 'US',
      language: 'en',
      authors: ['Zahra Tayeb'],
      media: 'https://i.insider.com/610e9ed738aff70018906a9a?width=1200&format=jpeg',
      is_opinion: false,
      twitter_account: null,
      _score: 23.376768,
      _id: 'cca4a69151591931dc0b69fc61b1e414',
    },
    {
      title:
        "Elon Musk Takes Digs At Blue Origin, Amazon CEO: Jeff Bezos Would Have Been 'On Pluto' If 'Lobbying And Lawyers' Worked",
      author: 'Madhukumar Warrier , Benzinga Staff Writer',
      published_date: '2021-08-12 07:35:09',
      published_date_precision: 'full',
      link: 'https://www.benzinga.com/news/21/08/22459230/elon-musk-takes-digs-at-blue-origin-amazon-ceo-jeff-bezos-would-have-been-on-pluto-if-lobbying-and-l',
      clean_url: 'benzinga.com',
      excerpt:
        'Tesla Inc. (NASDAQ: TSLA) and SpaceX CEO Elon Musk has taken potshots at Amazon.com Inc. (NASDAQ: AMZN) founder Jeff Bezos and his space company Blue Origin. What Happened: Musk...',
      summary:
        "Tesla Inc. (NASDAQ: TSLA) and SpaceX CEO Elon Musk has taken potshots at Amazon.com Inc. (NASDAQ: AMZN) founder Jeff Bezos and his space company Blue Origin.\nWhat Happened: Musk said on Twitter that Bezos would have been on Pluto now if 'lobbying and lawyers' were able to influence space missions.\nIf lobbying & lawyers could get u to orbit, Bezos would be on Pluto rn\n— Elon Musk (@elonmusk) August 12, 2021\nMusk also agreed with another Twitter user, who noted that Blue Origin's New Glenn launch ",
      rights: 'benzinga.com',
      rank: 2282,
      topic: 'finance',
      country: 'US',
      language: 'en',
      authors: ['Madhukumar Warrier'],
      media:
        'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/blue-origin-first-human-flight-l0-jeff-bezos-celebration.jpg',
      is_opinion: false,
      twitter_account: '@benzinga',
      _score: 23.292734,
      _id: '238c5a9647d852d85a2817d20cbe61a4',
    },
    {
      title: 'Tesla Cybertruck Production Delayed Until Next Year',
      author:
        'Entrepreneur Entrepreneur Empowering People in the Business of Changing the World | Entrepreneur® is dedicated to fueling the world’s visionary leaders compelled to make a difference through their innovative ideas, businesses, and points of view. View profile',
      published_date: '2021-08-11 05:39:34',
      published_date_precision: 'full',
      link: 'https://www.theepochtimes.com/tesla-cybertruck-production-delayed-until-next-year_3940413.html',
      clean_url: 'theepochtimes.com',
      excerpt:
        "Production on Tesla's Cybertruck has been delayed until 2022, according to a brief update on the company's website.",
      summary:
        "Tesla Cybertruck Production Delayed Until Next Year\n\nTesla CEO Elon Musk first unveiled the Cybertruck in 2019, saying they'd be done later this year\n\nProduction on Tesla's Cybertruck has been delayed until 2022, according to a brief update on the company's website.\n\nInterested customers who click 'Order Now' on the landing page for the company's first electric pickup see this message under 'Due Today': 'You will be able to complete your configuration as production nears in 2022.'\n\nTesla CEO Elo",
      rights: 'theepochtimes.com',
      rank: 1778,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['EntMagazine'],
      media: 'https://img.theepochtimes.com/assets/uploads/2018/08/02/tesla-1200x913.jpg',
      is_opinion: false,
      twitter_account: '@entrepreneur',
      _score: 23.254662,
      _id: '1871e0ce483b068758e98495c8031a84',
    },
    {
      title: 'Elon Musk dished out some free advice to rival carmaker Rivian: Get your',
      author: 'Grace Kay',
      published_date: '2021-08-12 07:32:00',
      published_date_precision: 'full',
      link: 'https://www.businessinsider.com/tesla-elon-musk-dishes-advice-to-rivian-get-plant-working-2021-8',
      clean_url: 'businessinsider.com',
      excerpt:
        'Rivian is scouting for a second US factory but has been forced to delay deliveries for a second time on its electric pickup truck.',
      summary:
        "Tesla CEO Elon Musk looks at his mobile phone. Joe Skipper/Reuters Tesla CEO Elon Musk has some advice for electric car startup Rivian – get your first factory 'working' before trying to expand into a second one.\nMusk commented on the issue on Twitter on Wednesday, following a Reuters report that Rivian is looking to build a second US plant and has scouted a location in Fort Worth, Texas. 'I'd recommend they get their first plant working,' Musk tweeted on Wednesday. 'It's insanely difficult to r",
      rights: 'businessinsider.com.au',
      rank: 110,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Grace Kay', 'Aug.'],
      media: 'https://i.insider.com/60279034b3c2a800183ccbf4?format=jpeg',
      is_opinion: false,
      twitter_account: '@BIAUS',
      _score: 22.954294,
      _id: 'd2c92cfcbdf7b31f5a8cf520cd2071be',
    },
    {
      title: "Biden Gang Didn't Invite Tesla to Electric Vehicle Event Because They Don't Employ Union Workers",
      author: 'Joe Hoft',
      published_date: '2021-08-07 07:15:00',
      published_date_precision: 'full',
      link: 'https://www.thegatewaypundit.com/2021/08/biden-gang-didnt-invite-tesla-electric-vehicle-event-dont-employ-union-workers/',
      clean_url: 'thegatewaypundit.com',
      excerpt:
        "(Above the Tesla pickup) The Biden gang held an event heralding US electric vehicles but decided not to invite Tesla because they don't employ union workers. Elon Musk shared in a tweet that Tesla was…",
      summary:
        "(Above the Tesla pickup)\nThe Biden gang held an event heralding US electric vehicles but decided not to invite Tesla because they don't employ union workers. Elon Musk shared in a tweet that Tesla was not invited to the Biden gang's event sponsoring electric vehicles.\n\nYeah, seems odd that Tesla wasn't invited\n— Elon Musk (@elonmusk) August 5, 2021\n\n\nTRENDING: Let Them Eat Cake: Obama Lied - Massive Party Tents Set Up on Martha Vineyard Compound in Advance of Lavish B-Day Bash on Saturday\n Press",
      rights: 'thegatewaypundit.com',
      rank: 7018,
      topic: 'politics',
      country: 'US',
      language: 'en',
      authors: ['Joe Hoft'],
      media: 'https://www.thegatewaypundit.com/wp-content/uploads/Tesla-Electric-Pickup-Truck.jpg',
      is_opinion: false,
      twitter_account: '@joehoft',
      _score: 22.873886,
      _id: 'f96afb9d87047727f8c8c189e1e4d8a9',
    },
    {
      title: "SpaceX completes stacking Starship for 1st orbital flight. Elon Musk says it's a 'dream come true.'",
      author: 'Zahra Tayeb',
      published_date: '2021-08-07 15:20:00',
      published_date_precision: 'full',
      link: 'https://news.yahoo.com/spacex-completes-stacking-starship-1st-152000480.html',
      clean_url: 'yahoo.com',
      excerpt:
        "Elon Musk's SpaceX stacked a Starship prototype rocket atop a Super Heavy rocket booster for the first time on Friday.",
      summary:
        'SpaceX founder Elon Musk. Hannibal Hanschke Pool / Getty Images\n\nSpaceX on Friday completed stacking its Starship rocket for its first attempt at orbital flight.\n\nCEO Elon Musk shared photos of the 400-foot spacecraft on Twitter.\n\n"Dream come true," Musk said.\n\nSee more stories on Insider\'s business page.\n\nElon Musk on Friday shared photos of SpaceX\'s Starship atop a Super Heavy rocket booster before its first orbital flight.\n\nAt about 400 feet tall, it was the biggest rocket ever constructed, B',
      rights: 'yahoo.com',
      rank: 30,
      topic: 'science',
      country: 'US',
      language: 'en',
      authors: ['Zahra Tayeb'],
      media:
        'https://s.yimg.com/ny/api/res/1.2/7VeW1AmecUUJ74ee460mgQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTIwMDA7aD0xNTAw/https://s.yimg.com/uu/api/res/1.2/PgKfozlh0uqwvF9I1LfgZA--~B/aD0zMjg0O3c9NDM3OTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/business_insider_articles_888/7458a76d4d3988960bd474e15db0b651',
      is_opinion: false,
      twitter_account: '@YahooNews',
      _score: 22.79524,
      _id: 'ed746e6f2ea902f206542a60590b9814',
    },
    {
      title: "SpaceX breaks record for world's tallest rocket",
      author: null,
      published_date: '2021-08-09 22:37:48',
      published_date_precision: 'full',
      link: 'https://www.kvue.com/article/news/local/texas/spacex-breaks-record-for-worlds-tallest-rocket/269-301c110f-d55c-4615-a431-ed1089d8b478',
      clean_url: 'kvue.com',
      excerpt: 'The Starship spacecraft stands at 475 feet, including the launch stand.',
      summary:
        "TEXAS, USA — Elon Musk has broken a new record, as his SpaceX Starship has officially become the world's tallest rocket, according to Space.com. It now stands at 395 feet – or 475 feet including the launch stand. But what Musk might be the most excited about is the fact this rocket is set to make its first-ever orbital test flight. The Starship could return science instruments even from deep in space. Its goal is to fly people to destinations like the moon, Mars and beyond. Over the weekend, Mus",
      rights: 'kvue.com',
      rank: 7876,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://media.kvue.com/assets/KVUE/images/78b769e9-c0a6-4116-b7ea-770b8dd74016/78b769e9-c0a6-4116-b7ea-770b8dd74016_1140x641.jpg',
      is_opinion: false,
      twitter_account: 'KVUE',
      _score: 22.60715,
      _id: '010ae237dd8a6f5341e135015373f523',
    },
    {
      title: "Elon Musk reveals Walter Isaacson, Steve Jobs' biographer, to write his story",
      author: null,
      published_date: '2021-08-07 15:14:00',
      published_date_precision: 'full',
      link: 'https://www.cnbctv18.com/world/elon-musk-reveals-walter-isaacson-steve-jobs-biographer-to-write-his-story-10290531.htm',
      clean_url: 'cnbctv18.com',
      excerpt: 'Walter Isaacson, who wrote the biography of Steve Jobs, will now pen the story of Tesla CEO Elon Musk',
      summary:
        'Elon Musk is getting another biography and this one will be penned by famous author Walter Isaacson, the billionaire announced on Twitter on August 5."If you\'re curious about Tesla, SpaceX & my general goings on, @WalterIsaacson is writing a biography," he tweeted.If you\'re curious about Tesla, SpaceX & my general goings on, @WalterIsaacson is writing a biography— Elon Musk (@elonmusk) August 5, 2021Isaacson, known for his best-selling biography of Apple co-founder Steve Jobs, has also written o',
      rights: 'cnbctv18.com',
      rank: 16951,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://images.cnbctv18.com/wp-content/uploads/2018/08/2018-08-13T131714Z_1_LYNXMPEE7C0YA_RTROPTP_3_AUTOSHOW-TESLA-MUSK.jpg',
      is_opinion: false,
      twitter_account: null,
      _score: 22.602423,
      _id: '7c0c9186233fed42a746ec0c93245209',
    },
    {
      title: 'Jim Cramer: Wait for Elon Musk Before You Sell Tesla Stock',
      author: 'Daniel Kuhn',
      published_date: '2021-08-10 16:26:04',
      published_date_precision: 'full',
      link: 'https://www.thestreet.com/jim-cramer/wait-elon-musk-judgement-tesla-stock-jim-cramer-says',
      clean_url: 'thestreet.com',
      excerpt:
        'Jim Cramer says he needs more information from Tesla before making a judgement on the stock following lackluster July deliveries in China.',
      summary:
        "Tesla  (TSLA) - Get Report delivered 8,621 China-made cars to the local market in July, down 69% from June amid a string of bad publicity paired from increased local competition. Jim Cramer told Action Alerts PLUS senior analyst Jeff Marks that before he can make a judgement on the news, he needs to hear a little more from Tesla CEO Elon Musk. \"One of the things I often find with Elon Musk is you'll make a judgement and it'll turn out there is something you didn't know. He always seems to confou",
      rights: 'thestreet.com',
      rank: 1376,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Daniel Kuhn'],
      media: 'https://www.thestreet.com/.image/t_share/MTgyMDUzNjEwNTAxMTg2ODg4/tesla-model-3.jpg',
      is_opinion: false,
      twitter_account: '@thestreet',
      _score: 22.558908,
      _id: 'ddce33b2206768122170e4b1f5598805',
    },
    {
      title: "SpaceX completes stacking Starship for 1st orbital flight. Elon Musk says it's a 'dream come true.'",
      author: null,
      published_date: '2021-08-07 16:15:00',
      published_date_precision: 'timezone unknown',
      link: 'https://www.msn.com/en-us/news/technology/spacex-completes-stacking-starship-for-1st-orbital-flight-elon-musk-says-it-s-a-dream-come-true/ar-AAN3fDI',
      clean_url: 'msn.com',
      excerpt:
        "Elon Musk's SpaceX stacked a Starship prototype rocket atop a Super Heavy rocket booster for the first time on Friday.",
      summary:
        '© Hannibal Hanschke Pool / Getty Images SpaceX founder Elon Musk. Hannibal Hanschke Pool / Getty Images\n\nSpaceX on Friday completed stacking its Starship rocket for its first attempt at orbital flight.\n\nCEO Elon Musk shared photos of the 400-foot spacecraft on Twitter.\n\n"Dream come true," Musk said.\n\nSee more stories on Insider\'s business page.\n\nElon Musk on Friday shared photos of SpaceX\'s Starship atop a Super Heavy rocket booster before its first orbital flight.\n\nAt about 400 feet tall, it wa',
      rights: 'msn.com',
      rank: 92,
      topic: 'science',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AAKeJZT.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg&x=2634&y=1438',
      is_opinion: false,
      twitter_account: null,
      _score: 22.522736,
      _id: 'c17dcd90d0a828f77d4545b44d2b2f2c',
    },
    {
      title: 'Steve Jobs 傳記作者 Walter Isaacson 確認為 Elon Musk 寫傳',
      author: 'Sanji Feng',
      published_date: '2021-08-06 08:25:40',
      published_date_precision: 'full',
      link: 'https://chinese.engadget.com/elon-musk-walter-isaacson-biography-083050703.html',
      clean_url: 'engadget.com',
      excerpt:
        'Steve Jobs 傳記作者 Walter Isaacson 確認為 Elon Musk 寫傳，實際上 Musk 在 2015 年已經有過一本傳記，但那之後的故事顯然值得再寫。',
      summary:
        'BERLIN, GERMANY DECEMBER 01: SpaceX owner and Tesla CEO Elon Musk poses on the red carpet of the Axel Springer Award 2020 on December 01, 2020 in Berlin, Germany. (Photo by Britta Pedersen-Pool/Getty Images)\n\n在 2011 年曾為 Steve Jobs 寫過傳記的 Walter Isaacson，現已確認會成為 Elon Musk 新傳記的作者。此前在六月時，Fox Business 曾報導過 Isaacson 與 Musk 商談合作可能性的流言。時至今日 Musk 自己發推證實了這一消息，並稱新書將涵蓋他在 Tesla、SpaceX 的工作以及「各種生活雜事」。\n\n實際上，在 2015 年已經有另一位作者 Ashlee Vance 為 Musk 寫過一本名為《Elon Musk: How the Billionaire CEO of SpaceX and Tesla is Sha',
      rights: 'copyright Oath 2021',
      rank: 319,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Sanji Feng'],
      media: 'https://s.yimg.com/os/creatr-uploaded-images/2021-08/24494670-f684-11eb-bdb6-d9f100a049a8',
      is_opinion: false,
      twitter_account: '@engadgetchinese',
      _score: 22.30792,
      _id: 'ab3c69dcffc2532226f8b53b5980b07a',
    },
    {
      title: 'Elon Musk Offers SpaceX Help To NASA As Spacesuits Make Bottleneck In 2024 Moon Landing',
      author: 'Shivdeep Dhaliwal',
      published_date: '2021-08-11 03:11:50',
      published_date_precision: 'full',
      link: 'http://feeds.benzinga.com/~r/benzinga/~3/7VJEsSHZuCY/elon-musk-offers-spacex-help-to-nasa-as-spacesuits-make-bottleneck-in-2024-moon-landing',
      clean_url: 'benzinga.com',
      excerpt:
        "Elon Musk said Tuesday that SpaceX can develop spacesuits for National Aeronautics and Space Administration's 2024 Moon mission \"if need be.'\nread more",
      summary:
        "Elon Musk said Tuesday that SpaceX can develop spacesuits for National Aeronautics and Space Administration's 2024 Moon mission \"if need be.'\n\nWhat Happened: Musk, who serves as CEO of both Tesla Inc (NASDAQ: TSLA) and SpaceX, made the comment while responding to a tweet by CNBC space reporter Michael Sheetz.\n\nSheetz pointed to the $420 million already spent on suit development and another $625 million expected to be spent on it, citing NASA's Inspector General.\n\nSpaceX could do it if need be — ",
      rights: 'benzinga.com',
      rank: 2282,
      topic: 'finance',
      country: 'US',
      language: 'en',
      authors: ['Shivdeep Dhaliwal'],
      media:
        'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/nasa-gywfpvi2jzm-unsplash.jpg',
      is_opinion: false,
      twitter_account: '@benzinga',
      _score: 22.234385,
      _id: '8267d46bded5d9a1a9fe6afce7dcc6be',
    },
    {
      title: "Tesla's Musk says must keep to schedule on European gigafactory",
      author: 'Reuters',
      published_date: '2021-08-12 08:42:07',
      published_date_precision: 'full',
      link: 'https://www.reuters.com/business/autos-transportation/teslas-musk-says-must-keep-schedule-european-gigafactory-minister-2021-08-12/',
      clean_url: 'reuters.com',
      excerpt:
        'Tesla (TSLA.O) CEO Elon Musk has made clear how important it is for the company to keep to its schedule for the construction of its European gigafactory in the German state of Brandenburg, its Economy…',
      summary:
        'SpaceX owner and Tesla CEO Elon Musk arrives on the red carpet for the automobile awards "Das Goldene Lenkrad" (The golden steering wheel) given by a German newspaper in Berlin, Germany, November 12, 2019. REUTERS/Hannibal HanschkeBERLIN, Aug 12 (Reuters) - Tesla (TSLA.O) CEO Elon Musk has made clear how important it is for the company to keep to its schedule for the construction of its European gigafactory in the German state of Brandenburg, its Economy Minister Joerg Steinbach said.Tesla also ',
      rights: 'reuters.com',
      rank: 88,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://www.reuters.com/resizer/cqMJyaU0Us__JXXe1hN96W-D9D0=/800x419/smart/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/PHEJOPAWUVJKVLDSZOGBA3FYOY.jpg',
      is_opinion: false,
      twitter_account: '@Reuters',
      _score: 22.209301,
      _id: 'ebeb4a998911e79cc1d81104947049bc',
    },
    {
      title: "Why Elon Musk Isn't Superman",
      author: 'Yves Smith',
      published_date: '2021-08-12 10:28:07',
      published_date_precision: 'full',
      link: 'https://www.nakedcapitalism.com/2021/08/why-elon-musk-isnt-superman.html',
      clean_url: 'nakedcapitalism.com',
      excerpt:
        'Why Elon Musk, despite having built significant operating companies, is still mainly in the bezzle business.',
      summary:
        "Yves here. I really wish Elon Musk was not as successful as he is in getting so much media attention that he can't be avoided unless you limit your Web surfing to non-stop cat videos. So as much as part of me does not want to add to his clippings file, this debunking is a welcome relief.\nBy Tim O'Reilly, the founder and CEO of O'Reilly Media Inc. His original business plan was simply 'interesting work for interesting people,' and that's worked out pretty well. He publishes books, runs conference",
      rights: 'nakedcapitalism.com',
      rank: 14070,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Yves Smith', 'Lambert Strether', 'Michael Ismoe', 'William Hunter Duncan'],
      media: 'https://www.nakedcapitalism.com/wp-content/uploads/2021/08/00-musk.png',
      is_opinion: false,
      twitter_account: '@yvessmith',
      _score: 22.194618,
      _id: 'f003f3991980f816adb6ee9cbbb55f70',
    },
    {
      title: "Why Elon Musk Isn't Superman",
      author: 'Yves Smith',
      published_date: '2021-08-12 10:28:07',
      published_date_precision: 'full',
      link: 'http://feedproxy.google.com/~r/nakedcapitalism/~3/ilp9itIUYLU/why-elon-musk-isnt-superman.html',
      clean_url: 'google.com',
      excerpt:
        'Why Elon Musk, despite having built significant operating companies, is still mainly in the bezzle business.',
      summary:
        "Yves here. I really wish Elon Musk was not as successful as he is in getting so much media attention that he can't be avoided unless you limit your Web surfing to non-stop cat videos. So as much as part of me does not want to add to his clippings file, this debunking is a welcome relief.\n\nBy Tim O'Reilly, the founder and CEO of O'Reilly Media Inc. His original business plan was simply 'interesting work for interesting people,' and that's worked out pretty well. He publishes books, runs conferenc",
      rights: 'google.com',
      rank: 1,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Yves Smith'],
      media: 'https://www.nakedcapitalism.com/wp-content/uploads/2021/08/00-musk.png',
      is_opinion: false,
      twitter_account: '@yvessmith',
      _score: 22.187923,
      _id: 'e35d67de307cdddaf01e213cfc3c25b1',
    },
    {
      title: "Tale Of Tesla, Elon Musk Is Inherently Dramatic And Compellingly Told In 'Power Play'",
      author: 'Camila Flamiano Domonoske Covers Cars',
      published_date: '2021-08-12 13:22:24',
      published_date_precision: 'full',
      link: 'https://www.npr.org/2021/08/12/1027032293/tale-of-tesla-elon-musk-is-inherently-dramatic-and-compellingly-told-in-power-pl?ft=nprml&f=1027032293',
      clean_url: 'npr.org',
      excerpt:
        "Perhaps most interesting in Tim Higgins' book are the hints at what might have been: Tesla could have built a plug-in hybrid, or sold itself to Google, or become a battery supplier.",
      summary:
        "Elon Musk has gotten a lot of things wrong. He's blown deadlines, pissed off regulators, driven away talented employees, and made unfulfilled promises that ran the gamut from unrealistic to absurd. But he got some things — some big, fortune-making and world-transforming things — right. He believed the world had an unmet appetite for electric cars. He thought a California startup could upend the global auto industry. And time and again, when Tesla's future seemed doomed, he (quite literally) gamb",
      rights: 'usf.edu',
      rank: 148,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Camila Flamiano Domonoske Covers Cars', 'Energy', "The Future Of Mobility For Npr'S Business Desk."],
      media:
        'https://npr.brightspotcdn.com/dims4/default/4217e55/2147483647/strip/true/crop/3180x1670+0+358/resize/1200x630!/quality/90/?url=https%3A%2F%2Fmedia.npr.org%2Fassets%2Fimg%2F2021%2F08%2F12%2Fgettyimages-1233956997-95b0990c50135442059409da1ccd02988cf6ba33.jpg',
      is_opinion: false,
      twitter_account: '@wusf',
      _score: 22.173916,
      _id: '769b65cba38947ae989c9b3da0ba18ae',
    },
    {
      title: "Tale Of Tesla, Elon Musk Is Inherently Dramatic And Compellingly Told In 'Power Play'",
      author: 'Camila Domonoske',
      published_date: '2021-08-12 13:24:00',
      published_date_precision: 'full',
      link: 'https://www.gpb.org/news/2021/08/12/tale-of-tesla-elon-musk-inherently-dramatic-and-compellingly-told-in-power-play',
      clean_url: 'gpb.org',
      excerpt:
        "Perhaps most interesting in Tim Higgins' book are the hints at what might have been: Tesla could have built a plug-in hybrid, or sold itself to Google, or become a battery supplier.",
      summary:
        "Elon Musk has gotten a lot of things wrong. He's blown deadlines, pissed off regulators, driven away talented employees, and made unfulfilled promises that ran the gamut from unrealistic to absurd.\n \nBut he got some things — some big, fortune-making and world-transforming things — right. He believed the world had an unmet appetite for electric cars. He thought a California startup could upend the global auto industry. And time and again, when Tesla's future seemed doomed, he (quite literally) ga",
      rights: 'gpb.org',
      rank: 16740,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Camila Domonoske', 'Shannon Bond', 'Lauren Sommer', 'Daniel Wood', 'Adam Frank'],
      media:
        'https://www.gpb.org/sites/default/files/styles/three_two_702x468/public/npr_story_images/2021/08/12/tesla-e264693726a216d1116ac4ff0557766d156de20f.jpg?h=81e13469&itok=Yun2TW9A',
      is_opinion: false,
      twitter_account: null,
      _score: 22.123098,
      _id: 'a13a70970da63f089f46d81a1d87d003',
    },
    {
      title: 'Elon Musk Supports Crypto Community Ahead of Crucial Taxation Vote in the US',
      author: 'Jordan Lyanchev',
      published_date: '2021-08-07 07:02:48',
      published_date_precision: 'full',
      link: 'https://cryptopotato.com/elon-musk-supports-crypto-community-ahead-of-crucial-taxation-vote-in-the-us/',
      clean_url: 'cryptopotato.com',
      excerpt:
        'There\'s no existing crisis in the cryptocurrency market now that requires "hasty" regulations, said Tesla\'s CEO Elon Musk.',
      summary:
        "The crypto community continues to rally the troops just hours ahead of the crucial vote on digital asset taxation from US Congress. This time, they have received support from one of the most influential people today – Elon Musk.\n\nCryptoPotato reported yesterday the controversy that arose from US authorities in regards to the country's attempt to regulate and implement taxes on the digital asset industry.\nIn shorts, Senators Mark Warner and Rob Portman proposed an amendment that wants to tax almo",
      rights: 'cryptopotato.com',
      rank: 32853,
      topic: 'finance',
      country: 'US',
      language: 'en',
      authors: ['Jordan Lyanchev'],
      media: 'https://cryptopotato.com/wp-content/uploads/2021/05/ElonMusk.jpg',
      is_opinion: false,
      twitter_account: '@Crypto_Potato',
      _score: 22.100105,
      _id: 'e993b8e82adc77f65a9466b3bcae6fe3',
    },
    {
      title: 'The Elan of Elon Musk',
      author:
        'Andrew Ross Sorkin, Jason Karaian, Sarah Kessler, Stephen Gandel, Lauren Hirsch, Ephrat Livni and Anna Schaverien',
      published_date: '2021-08-12 11:53:21',
      published_date_precision: 'full',
      link: 'https://www.nytimes.com/2021/08/12/business/dealbook/carson-block-tesla-elon-musk.html',
      clean_url: 'nytimes.com',
      excerpt:
        "A longtime critic of the Tesla chief executive explains why his bets against the car company haven't paid off.",
      summary:
        "Continue reading the main storyA longtime critic of the Tesla chief executive explains why his bets against the car company haven't paid off.Aug. 12, 2021, 7:53 a.m. ETImageA man with élan, even his detractors admit.Credit...Odd Andersen/Agence France-Presse — Getty ImagesMuch has been written about Carson Block, the volatile and sometimes venomous short-seller who runs Muddy Waters Capital. Now, Block is penning some rare words of his own.Block just sent clients his first shareholder letter sin",
      rights: 'nytimes.com',
      rank: 39,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [
        'Andrew Ross Sorkin',
        'Jason Karaian',
        'Sarah Kessler',
        'Stephen Gandel',
        'Lauren Hirsch',
        'Ephrat Livni',
        'Anna Schaverien',
      ],
      media:
        'https://static01.nyt.com/images/2021/08/12/business/12db-newsletter-musk/12db-newsletter-musk-facebookJumbo.jpg',
      is_opinion: false,
      twitter_account: '@nytimes',
      _score: 22.093077,
      _id: '134bc257caf59e69cf226f7a694c8f04',
    },
    {
      title: "Elon Musk is ‘desperate' to construct an electric plane, but is concerned that his 'brain may explode.'",
      author: 'Helena Sutan',
      published_date: '2021-08-06 15:41:44',
      published_date_precision: 'full',
      link: 'https://en.brinkwire.com/science/elon-musk-is-desperate-to-construct-an-electric-plane-but-is-concerned-that-his-brain-may-explode/',
      clean_url: 'brinkwire.com',
      excerpt:
        "Elon Musk is ‘desperate' to construct an electric plane, but is concerned that his 'brain may explode.' ELON MUSK is 'desperate' to try his hand at constructing an all-electric, supersonic jet plane,…",
      summary:
        "Elon Musk is ‘desperate' to construct an electric plane, but is concerned that his 'brain may explode.'\nELON MUSK is 'desperate' to try his hand at constructing an all-electric, supersonic jet plane, but his workload prevents him from doing so.\nElon Musk isn't content to just sit around and watch the world go by; he's revealed some details about the projects he'd like to work on. Although the South African billionaire's hands are full with the launch of Tesla's Model S Plaid and SpaceX's Starshi",
      rights: 'brinkwire.com',
      rank: 72979,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Helena Sutan'],
      media: 'https://en.brinkwire.com/nerede/uploads/2020/12/faviconV2.jpg',
      is_opinion: false,
      twitter_account: null,
      _score: 21.907677,
      _id: '4d4eb71b15ac20abcecd382af5f1419d',
    },
    {
      title: "Elon Musk on reported NASA space suit delays: 'SpaceX could do it'",
      author: null,
      published_date: '2021-08-10 21:24:18',
      published_date_precision: 'full',
      link: 'https://thehill.com/policy/technology/567239-elon-musk-on-reported-nasa-space-suit-delays-spacex-could-do-it',
      clean_url: 'thehill.com',
      excerpt:
        "SpaceX founder Elon Musk on Tuesday said that his company could help develop NASA's new spacesuits after a watchdog report noted significant delays in design and testing that may prevent the agency…",
      summary:
        "SpaceX founder Elon MuskElon Reeve MuskNow someone wants to slap a SPACE Tax on Jeff Bezos, Elon Musk, et al How not to waste billion in broadband subsidies The Hill's Sustainability Report: Extreme heat threatens Olympics of yesteryear — and today MORE on Tuesday said that his company could help develop NASA's new spacesuits after a watchdog report noted significant delays in design and testing that may prevent the agency from meeting its goal of returning astronauts to the moon by 2024. NASA's",
      rights: 'thehill.com',
      rank: 587,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media: 'https://thehill.com/sites/default/files/muskelon_12012020_1.jpg',
      is_opinion: false,
      twitter_account: null,
      _score: 21.827227,
      _id: 'c9909b204474d3335929883fdb3ab6df',
    },
    {
      title: "SpaceX's Fully-Stacked Starship Is the Biggest Rocket Ever Built",
      author: 'Rosie Perper',
      published_date: '2021-08-07 00:43:34',
      published_date_precision: 'full',
      link: 'https://hypebeast.com/2021/8/spacex-fully-stacked-starship-photos-super-heavy-booster',
      clean_url: 'hypebeast.com',
      excerpt: 'The two Starship segments stand at nearly 400 feet.',
      summary:
        'Elon Musk on Friday released photos of his Starship rocket fully-loaded up atop the Super Heavy Booster 4, standing at an impressive combined height of nearly 400 feet tall. The stacked construction of the two segments at the Starbase facility in Boca Chica, Texas, easily makes it the biggest rocket ever constructed, according to the BBC. \nPhotos tweeted out by Musk show the colossal pieces coming together for the first time.\n\nStarship Fully Stacked pic.twitter.com/Fs88RNsmfH\n— Elon Musk (@elonm',
      rights: 'hypebeast.com',
      rank: 3348,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [
        'Rosie Perper',
        'Dylan Kelly',
        'Joyce Li',
        'Nicolaus Li',
        'Shawn Ghassemitari',
        'Sarah Kearns',
        'Ross Dwyer',
        'Elliot Santiago',
      ],
      media:
        'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2021%2F08%2FSpaceX%E2%80%99s-Fully-Stacked-Starship-Is-the-Biggest-Rocket-Ever-Built-tw.jpg?w=960&cbr=1&q=90&fit=max',
      is_opinion: false,
      twitter_account: '@hypebeast',
      _score: 21.809534,
      _id: '1f52bed3e5842dc540764301f2c4b7f8',
    },
    {
      title: "Inside Elon Musk's tiny 375sq ft unit box home, what makes the billionaire's house special",
      author: 'Republic World',
      published_date: '2021-08-10 04:37:00',
      published_date_precision: 'full',
      link: 'https://www.republicworld.com/business-news/international-business/inside-elon-musks-tiny-375sq-ft-unit-box-home-what-makes-the-billionaires-house-special.html',
      clean_url: 'republicworld.com',
      excerpt:
        'The Space X CEO owns only one home which is his Bay Area events house. However, it is his tiny prefab house in Boca Chic which is far more interesting.',
      summary:
        "Tech billionaire Elon Musk has established himself as a business magnate and one of the richest persons in the world. But, did you know that Musk lives in a fairly modest way as per billionaire standards? The Space X CEO owns only one home which is his Bay Area events house. However, it is his tiny prefab house in Boca Chic which is far more interesting. Elon Musk's primary house is a $50k property in Boca Chica that he rents from SpaceX. The 375-square-foot house is a tiny prefabricated home by",
      rights: 'republicworld.com',
      rank: 9700,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Republic World'],
      media: 'https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/rzxnxo4ds2i7vvtt_1628569730.jpeg',
      is_opinion: false,
      twitter_account: '@republic',
      _score: 21.805996,
      _id: 'ced8ffc416656fa3b82b3b03d167a628',
    },
    {
      title: "SpaceX stacks Starship atop massive booster for 1st time to make the world's tallest rocket",
      author: 'Elizabeth Howell - Contributing Writer',
      published_date: '2021-08-06 15:20:06',
      published_date_precision: 'full',
      link: 'https://www.space.com/spacex-starship-super-heavy-booster-stacked-1st-time',
      clean_url: 'space.com',
      excerpt: "It's taller than NASA's Saturn V moon rocket.",
      summary:
        "SpaceX's first orbital Starship SN20 is stacked atop its massive Super Heavy Booster 4 for the first time on Aug. 4, 2021 at the company's Starbase facility near Boca Chica Village in South Texas. They stood 395 feet tall, taller than NASA's Saturn V moon rocket. (Image credit: SpaceX/Elon Musk via Twitter)SpaceX's newest Starship prototype was briefly placed atop of its massive booster for the first time on Friday (Aug. 6), setting a new record for the world's tallest rocket ahead of a planned ",
      rights: 'space.com',
      rank: 987,
      topic: 'science',
      country: 'US',
      language: 'en',
      authors: ['Elizabeth Howell'],
      media: 'https://cdn.mos.cms.futurecdn.net/op4NjVfPrXRqkrkNb39Vf5-1200-80.jpg',
      is_opinion: false,
      twitter_account: '@SPACEdotcom',
      _score: 21.796837,
      _id: '2b7ede0e9c0019f7048afdbc52b77257',
    },
    {
      title:
        "Elon Musk mocks Blue Origin's moon lander after the company argued against SpaceX winning a $2.9 billion NASA contract",
      author: 'Kate Duffy',
      published_date: '2021-08-12 16:22:37',
      published_date_precision: 'full',
      link: 'https://news.yahoo.com/elon-musk-mocks-blue-origins-162237517.html',
      clean_url: 'yahoo.com',
      excerpt:
        'SpaceX CEO Musk tweeted a photo of Blue Origin\'s lunar lander with its middle section seemingly deflated. "Somehow, this wasn\'t convincing," he said.',
      summary:
        'Blue Origin founder Jeff Bezos and SpaceX CEO Elon Musk. REUTERS/Joshua Roberts\n\nElon Musk mocked Blue Origin after it attacked NASA for awarding SpaceX a moon-lander contract.\n\nMusk tweeted a photo of a Blue Origin moon lander with the words: "Somehow, this wasn\'t convincing."\n\nBlue Origin says NASA gave SpaceX "preferential treatment" for the moon-lander contract.\n\nSee more stories on Insider\'s business page.\n\nElon Musk on Thursday mocked a photo of Blue Moon, the moon lander created by Jeff B',
      rights: 'yahoo.com',
      rank: 30,
      topic: 'tech',
      country: 'US',
      language: 'en',
      authors: ['Kate Duffy'],
      media:
        'https://s.yimg.com/uu/api/res/1.2/VW8oLeY_fDMZKOjTxZ5W1g--~B/aD05MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/business_insider_articles_888/820471310c5d0ba02ec8cb7217d2f697',
      is_opinion: false,
      twitter_account: '@YahooNews',
      _score: 21.72858,
      _id: 'f488b696d60f7486186be486afeb7080',
    },
    {
      title: 'So did you know that Elon Musk has his own teams that try to boost his image online?',
      author: null,
      published_date: '2021-08-06 11:49:15',
      published_date_precision: 'full',
      link: 'https://forums.macrumors.com/threads/so-did-you-know-that-elon-musk-has-his-own-teams-that-try-to-boost-his-image-online.2306717/',
      clean_url: 'macrumors.com',
      excerpt:
        'By writing positive messages about him, upvoting positive and downvoting negative press and posts about him on social media platforms, etc. He hires them to boost his image basically. So a guy just…',
      summary:
        'By writing positive messages about him, upvoting positive and downvoting negative press and posts about him on social media platforms, etc.\nHe hires them to boost his image basically. So a guy just made an account to downvote something negative and upvote something positive about Musk in a random thread. He literally just made a random account to do just that. Is it part of Musk‘s internet army or just Musk himself? I guess we‘ll never know. I added some screenshots as proof. \nThis was the threa',
      rights: 'macrumors.com',
      rank: 1349,
      topic: 'tech',
      country: 'US',
      language: 'en',
      authors: [],
      media: 'https://forums.macrumors.com/attachments/fbbdab72-08b0-47b3-8659-0cdd7a748091-jpeg.1815480/',
      is_opinion: false,
      twitter_account: null,
      _score: 21.674307,
      _id: '64af062f0538da99587585b5f3ff4e0d',
    },
    {
      title: 'SpaceX Completes Stacking Two Giant Starship Stages for 1st Orbital Flight: Photos',
      author: 'Sissi Cao',
      published_date: '2021-08-06 16:30:42',
      published_date_precision: 'full',
      link: 'https://observer.com/2021/08/starship-complete-stacking-upper-stage-sn20-super-heavy-booster-orbital-test/',
      clean_url: 'observer.com',
      excerpt: "It's the largest rocket ever built to go to space.",
      summary:
        "Starship SN20 stacked on top of a Super Heavy B4 booster at SpaceX's Starbase test site. Cosmic Perspective/Twitter\nAt SpaceX's 'Starbase' test site in the remote beach town of Boca Chica in southern Texas, workers have been laboring around the clock for days preparing for Starship's first orbital flight. On Friday morning, they completed one of the final and most challenging assembly step: stacking the 150-foot-tall first stage SN20 on top of an even bigger booster, the 230-foot-tall Super Heav",
      rights: 'observer.com',
      rank: 873,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [
        'Sissi Cao',
        'Sissi Cao Is A Business Reporter For Observer. Previously',
        'She Covered Institutional Finance For Trusted Insight. She Is A Graduate The University Of Maryland',
        'Is Originally Shanghai',
        'China. Follow Her On Twitter',
        'Https',
        'Observer.Com Wp-Content Uploads Sites Sissi-Profile.Jpg Quality W Strip',
      ],
      media:
        'https://observer.com/wp-content/uploads/sites/2/2021/08/E8HBQOHVIAM3mV3-e1628261571591.jpeg?quality=80&strip',
      is_opinion: false,
      twitter_account: '@observer',
      _score: 21.654078,
      _id: 'd12e728a649073a7c25fb54c165c9463',
    },
    {
      title:
        'Elon Musk dished out some free advice to rival carmaker Rivian: Get your "first plant working" before making plans to expand',
      author: 'Grace Kay',
      published_date: '2021-08-12 17:32:10',
      published_date_precision: 'full',
      link: 'https://www.businessinsider.com/tesla-elon-musk-dishes-advice-to-rivian-get-plant-working-2021-8',
      clean_url: 'businessinsider.com',
      excerpt:
        'Rivian is scouting for a second US factory but has been forced to delay deliveries for a second time on its electric pickup truck.',
      summary:
        'Tesla CEO Elon Musk has some advice for electric car startup Rivian — get your first factory "working" before trying to expand into a second one.Musk commented on the issue on Twitter on Wednesday, following a Reuters report that Rivian is looking to build a second US plant and has scouted a location in Fort Worth, Texas."I\'d recommend they get their first plant working," Musk tweeted on Wednesday. "It\'s insanely difficult to reach volume production at affordable unit cost."—Elon Musk (@elonmusk',
      rights: 'Insider',
      rank: 110,
      topic: 'business',
      country: 'US',
      language: 'en',
      authors: ['Grace Kay'],
      media: 'https://i.insider.com/611553bc3dd01000199d6403?width=1200&format=jpeg',
      is_opinion: false,
      twitter_account: '@CarsInsider',
      _score: 21.559889,
      _id: '52ec1f0e954307e6197feb4acae10427',
    },
    {
      title: 'Elon Musk reportedly lives in this tiny $ 50,000 house',
      author: null,
      published_date: '2021-08-10 15:50:21',
      published_date_precision: 'full',
      link: 'https://www.mccourier.com/elon-musk-reportedly-lives-in-this-tiny-50000-house/',
      clean_url: 'mccourier.com',
      excerpt: 'Imagine if you were one of the richest people on the planet. What would you do with your wealth? Sur',
      summary:
        'Imagine if you were one of the richest people on the planet. What would you do with your wealth? Surely you are buying a magnificent villa with several rooms, a huge swimming pool and a huge garden? Maybe … but it appears that this is not the case with Elon Musk, the CEO of SpaceX and Tesla. In fact, according to information from the businessinsider site, the American businessman has bought a tiny house! One of the richest men would live in a micro house For some time now, tiny houses, i.e. tiny',
      rights: 'mccourier.com',
      rank: 50941,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://www.mccourier.com/wp-content/uploads/2021/08/hitek_f97848459b931ed9e7863935489eac60_1628590977-780x470.png',
      is_opinion: false,
      twitter_account: null,
      _score: 21.527681,
      _id: 'b51ea8365d69116f2427256a2ca1ec18',
    },
    {
      title: '10 Tweets That Moved Markets In 2021',
      author: 'Priya Nigam',
      published_date: '2021-08-09 21:26:30',
      published_date_precision: 'full',
      link: 'https://www.benzinga.com/markets/cryptocurrency/21/08/22398419/10-tweets-that-moved-markets-in-2021',
      clean_url: 'benzinga.com',
      excerpt:
        'The bull and bear markets and everything in between is still driven mostly by comments or activities by Wall Street insiders, including financial a...',
      summary:
        "The bull and bear markets and everything in between is still driven mostly by comments or activities by Wall Street insiders, including financial analysts, investment strategists and portfolio managers.\nBut, we can't overlook the impact of social media influencers who can move market sentiment with a single Tweet.\nHere are the top tweets that moved the markets so far in 2021.\n1. Elon Musk: Bitcoin Rally \nStarting on Jan. 29, Tesla CEO Elon Musk drove crypto prices higher when he changed his Twit",
      rights: 'benzinga.com',
      rank: 2282,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Priya Nigam'],
      media:
        'https://cdn2.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/alexander-shatov-k1xf2d7jwus-unsplash_4.jpg?width=720',
      is_opinion: false,
      twitter_account: '@benzinga',
      _score: 21.5171,
      _id: 'e0723030a66eb2182477aac2f0bcd379',
    },
    {
      title: 'Elon Musk Lives In a $50k Tiny Home... Ummmm WTF???  HITS 96.1',
      author: null,
      published_date: '2021-08-10 17:30:00',
      published_date_precision: 'timezone unknown',
      link: 'https://power961.iheart.com/featured/ethan-cole/content/2021-08-10-elon-musk-lives-in-a-50k-tiny-home-ummmm-wtf/',
      clean_url: 'iheart.com',
      excerpt: 'Elon Musk Lives In a $50k Tiny Home... Ummmm WTF???',
      summary:
        "You've probably herd of the billionaire Tesla tycoon Elon Musk by now right? Maybe this will jog your memory... Dude literally blazed one up with Joe Rogan on his podcast. He's also been known to pump and dump crypto like Dogecoin. Anyway, the important piece of information you need for this story is that Elon Musk is really rich... Like really really rich. I think I saw somewhere that said he's worth like $170 BILLION with a BBBBB. So that's the only info you need. And now I'm sure you'll be sh",
      rights: 'iheart.com',
      rank: 883,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://i.iheart.com/v3/re/assets.getty/61129ffe63c683dd792bedb3?ops=gravity(%22north%22),fit(740,416),quality(65)',
      is_opinion: false,
      twitter_account: '@itsethancole',
      _score: 21.478327,
      _id: '07d490f13d22208df04e3039577f38cb',
    },
    {
      title: 'Elon Musk Lives In a $50k Tiny Home... Ummmm WTF???  Y100',
      author: null,
      published_date: '2021-08-10 20:30:00',
      published_date_precision: 'timezone unknown',
      link: 'https://power961.iheart.com/featured/ethan-cole/content/2021-08-10-elon-musk-lives-in-a-50k-tiny-home-ummmm-wtf/',
      clean_url: 'iheart.com',
      excerpt: 'Elon Musk Lives In a $50k Tiny Home... Ummmm WTF???',
      summary:
        "You've probably herd of the billionaire Tesla tycoon Elon Musk by now right? Maybe this will jog your memory... Dude literally blazed one up with Joe Rogan on his podcast. He's also been known to pump and dump crypto like Dogecoin. Anyway, the important piece of information you need for this story is that Elon Musk is really rich... Like really really rich. I think I saw somewhere that said he's worth like $170 BILLION with a BBBBB. So that's the only info you need. And now I'm sure you'll be sh",
      rights: 'iheart.com',
      rank: 883,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: [],
      media:
        'https://i.iheart.com/v3/re/assets.getty/61129ffe63c683dd792bedb3?ops=gravity(%22north%22),fit(740,416),quality(65)',
      is_opinion: false,
      twitter_account: '@itsethancole',
      _score: 21.223646,
      _id: 'e7d2cdc20c1b5398f6979f1d444790e6',
    },
    {
      title: 'Elon Musk Plans to Put Billboards in Space and People Want to Shoot Them at the Sun',
      author: 'Samson Amore',
      published_date: '2021-08-09 23:40:00',
      published_date_precision: 'full',
      link: 'https://www.yahoo.com/entertainment/elon-musk-plans-put-billboards-234000769.html',
      clean_url: 'yahoo.com',
      excerpt:
        "It turns out Elon Musk doesn't just want to send billionaires to space, he also wants to send advertising. And that idea isn't sitting well with earthbound critics. Business Insider reports the plan is for Musk's SpaceX to work with Geometric Energy Corp., a Canadian-based company, to send square-shaped CubeSat satellite, with one side used as a display screen, into space by 2022. The satellite would allow people or companies to blow what's likely a pretty hefty fee in order to project advertisi",
      summary:
        "Elon Musk Plans to Put Billboards in Space and People Want to Shoot Them at the Sun\n\nIt turns out Elon Musk doesn't just want to send billionaires to space, he also wants to send advertising. And that idea isn't sitting well with earthbound critics.\n\nBusiness Insider reports the plan is for Musk's SpaceX to work with Geometric Energy Corp., a Canadian-based company, to send square-shaped CubeSat satellite, with one side used as a display screen, into space by 2022. The satellite would allow peop",
      rights: 'yahoo.com',
      rank: 30,
      topic: 'business',
      country: 'US',
      language: 'en',
      authors: ['Samson Amore'],
      media:
        'https://s.yimg.com/uu/api/res/1.2/rpXQ0JEx1L7OHy6R79kblA--~B/aD00MDA7dz02MjA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/thewrap.com/c22074f5042b962423dab28a3297b9c1',
      is_opinion: false,
      twitter_account: '@Yahoo',
      _score: 21.220127,
      _id: '9aa9f1475d290e5b01703cc894f76890',
    },
    {
      title: 'Tesla sales cratered in China',
      author: 'Chris Isidore',
      published_date: '2021-08-10 16:18:27',
      published_date_precision: 'full',
      link: 'https://www.cnn.com/2021/08/10/investing/tesla-china-sales/index.html',
      clean_url: 'cnn.com',
      excerpt:
        "Tesla sales dropped sharply in China, according to a trade group report, suggesting it is losing ground in the world's largest market for both traditional and electric vehicles.",
      summary:
        "CHICAGO, IL - JUNE 14: Engineer and tech entrepreneur Elon Musk of The Boring Company listens as Chicago Mayor Rahm Emanuel talks about constructing a high speed transit tunnel at Block 37 during a news conference on June 14, 2018 in Chicago, Illinois. Musk said he could create a 16-passenger vehicle to operate on a high-speed rail system that could get travelers to and from downtown Chicago and O'hare International Airport under twenty minutes, at speeds of over 100 miles per hour. (Photo by Jo",
      rights: 'Copyright (c) 2021 Turner Broadcasting System, Inc. All Rights Reserved.',
      rank: 60,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Chris Isidore'],
      media:
        'https://cdn.cnn.com/cnnnext/dam/assets/210810081959-restricted-tesla-factory-shanghai-china-07-11-2021-super-169.jpg',
      is_opinion: false,
      twitter_account: '@CNNbusiness',
      _score: 21.13863,
      _id: 'fe3cb863718413596898af72e80fe0af',
    },
    {
      title:
        'Elon Musk reportedly lives in a $50,000 prefab tiny home that already has a 100,000-unit waitlist — see inside',
      author: 'bchang@businessinsider.com (Brittany Chang,Tim Levin)',
      published_date: '2021-08-08 12:08:00',
      published_date_precision: 'full',
      link: 'https://www.businessinsider.com/elon-musk-tiny-home-prefab-boxabl-casita-50000-person-waitlist-2021-8',
      clean_url: 'businessinsider.com',
      excerpt:
        'Boxabl had a waitlist of about 40,000 people before the Elon Musk rumors began. Now, its list has jumped to 47,000 who want over 100,000 tiny homes.',
      summary:
        'A photo shared with Insider appears to show Boxabl delivering a Casita to SpaceX. Jorge Ramirez More: Elon Musk tiny home Business Visual Features Boxabl It indicates an expandable section or menu, or sometimes previous / next navigation options.',
      rights: 'Insider',
      rank: 110,
      topic: 'business',
      country: 'US',
      language: 'en',
      authors: ['Brittany Chang,Tim Levin'],
      media: 'https://i.insider.com/610d4cb52a24d000186212a7?width=1200&format=jpeg',
      is_opinion: false,
      twitter_account: '@sai',
      _score: 21.073744,
      _id: 'f9c48212d4bd3f37d2ff7a2ec5eea61e',
    },
    {
      title:
        "Elon Musk mocks Blue Origin's moon lander after the company argued against SpaceX winning a $2.9 billion NASA contract",
      author: 'Kate Duffy',
      published_date: '2021-08-12 16:22:37',
      published_date_precision: 'full',
      link: 'https://www.businessinsider.com/elon-musk-mocks-bezos-blue-origin-lunar-lander-spacex-nasa-2021-8',
      clean_url: 'businessinsider.com',
      excerpt:
        'SpaceX CEO Musk tweeted a photo of Blue Origin\'s lunar lander with its middle section seemingly deflated. "Somehow, this wasn\'t convincing," he said.',
      summary:
        "Elon Musk on Thursday mocked a photo of Blue Moon, the moon lander created by Jeff Bezos' aerospace company, Blue Origin.His tweet came hours after Blue Origin once again criticized NASA for awarding SpaceX an exclusive $2.9 billion contract to land humans on the moon.Blue Origin said it would continue to challenge NASA's decision and repeated its claims that SpaceX got \"preferential treatment.\"In response to Blue Origin's statement, tweeted by Washington Post reporter Christian Davenport, Musk ",
      rights: 'Insider',
      rank: 110,
      topic: 'business',
      country: 'US',
      language: 'en',
      authors: ['Kate Duffy'],
      media: 'https://i.insider.com/60f68f55bc757c001904bce7?width=1200&format=jpeg',
      is_opinion: false,
      twitter_account: '@sai',
      _score: 21.015982,
      _id: 'b971cc230c71b5246f582941130f800e',
    },
    {
      title: 'Elon Musk Fires At Tesla Rival Rivian: Recommend They Get First Plant Working Before Jumping On Second',
      author: 'Rachit Vats , Benzinga Staff Writer',
      published_date: '2021-08-12 06:04:47',
      published_date_precision: 'full',
      link: 'https://www.benzinga.com/news/21/08/22459194/elon-musk-fires-at-tesla-rival-rivian-recommend-they-get-first-plant-working-before-jumping-on-secon',
      clean_url: 'benzinga.com',
      excerpt:
        'Tesla Inc (NASDAQ: TSLA) CEO Elon Musk has a piece of advice for Amazon.com Inc (NASDAQ: AMZN) and Ford Motor Co (NYSE: F)-backed electric vehicle maker Rivian - learn from your...',
      summary:
        "Tesla Inc (NASDAQ: TSLA) CEO Elon Musk has a piece of advice for Amazon.com Inc (NASDAQ: AMZN) and Ford Motor Co (NYSE: F)-backed electric vehicle maker Rivian - learn from your mistakes before rushing to build a second plant.\nWhat Happened: Rivian is reportedly investing at least $5 billion to build a second electric vehicle factory near Fort Worth, Texas. The manufacturing plant, codenamed 'Project Terra,' will have an annual capacity of 200,000 electric vehicles and is expected to create at l",
      rights: 'benzinga.com',
      rank: 2282,
      topic: 'finance',
      country: 'US',
      language: 'en',
      authors: ['Rachit Vats'],
      media:
        'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/16660212029_a697a53075_o_3.jpg',
      is_opinion: false,
      twitter_account: '@benzinga',
      _score: 20.985073,
      _id: '9d7a3900f6ff171dbccb65ff5eadca8e',
    },
    {
      title: "Tesla not invited for United States Electric Vehicle Summit, 'seems odd' Elon Musk says",
      author: 'Republic World',
      published_date: '2021-08-06 06:24:00',
      published_date_precision: 'full',
      link: 'https://www.republicworld.com/auto-news/cars/tesla-not-invited-for-united-states-electric-vehicle-summit-seems-odd-elon-musk-says.html',
      clean_url: 'republicworld.com',
      excerpt:
        "The White House, on Thursday, held an ambitious meeting of electric vehicle (EV) makers but sans the country's largest EV manufacturer- Tesla.",
      summary:
        "The White House, on Thursday, held an ambitious meeting of electric vehicle (EV) makers but sans the country's largest EV manufacturer- Tesla. The rendezvous hosted by President Joe Biden witnessed the presence of executives and officials from General Motors(GM) and Ford (F) as well as Stellantis, the company formed by a merger between Fiat Chrysler and France's PSA. All three manufacturers are a sliver of the country's total EV production but it is imperative to note that Tesla is a prime manuf",
      rights: 'republicworld.com',
      rank: 9700,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Republic World'],
      media: 'https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/0pt87ft7pyfwwi5o_1628230606.jpeg',
      is_opinion: false,
      twitter_account: '@republic',
      _score: 20.87285,
      _id: '065ca7bdeda13e71b5907f9e496fad44',
    },
    {
      title: "Tesla's Cybertruck production delayed to 2022; Read about electric pickup truck's features",
      author: 'Republic World',
      published_date: '2021-08-09 03:48:00',
      published_date_precision: 'full',
      link: 'https://www.republicworld.com/auto-news/cars/teslas-cybertruck-production-delayed-to-2022-read-about-electric-pickup-trucks-features.html',
      clean_url: 'republicworld.com',
      excerpt:
        "Tesla's much-awaited Cybertruck production has been delayed to 2022. With an impenetrable steel body, the vehicle is a one-of-a-kind goods carrier.",
      summary:
        "The Tesla Cybertruck had garnered much attention when it was first announced by the company's CEO Elon Musk in November 2019. Since then, auto enthusiasts, as well as EV fans, have been on the wait for new updates. Sadly though, Tesla has confirmed that the release of the Cybertruck electric pickup truck is delayed to 2022. The company had previously hinted at a market release by the end of 2021.Tesla Cybertruck timeline pushedEver since its announcement, Tesla has been falling behind on the tim",
      rights: 'republicworld.com',
      rank: 9700,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Republic World'],
      media: 'https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/axsivmmmdcgdzc0c_1628478573.jpeg',
      is_opinion: false,
      twitter_account: '@republic',
      _score: 20.803682,
      _id: '2c7ea830e32526cbb44cdc4288d135e2',
    },
    {
      title: 'Elon Musk Delays Tesla Cybertruck to 2022',
      author: 'Lucas Nolan',
      published_date: '2021-08-11 16:58:50',
      published_date_precision: 'full',
      link: 'https://www.breitbart.com/tech/2021/08/11/elon-musk-delays-tesla-cybertruck-to-2022/',
      clean_url: 'breitbart.com',
      excerpt:
        'Tesla has reportedly delayed the release of its Cybertruck electric pickup until 2022. The odd-looking truck is just one of several Tesla models that have been delayed into next year.',
      summary:
        "Tesla has reportedly delayed the release of its Cybertruck electric pickup until 2022. The odd-looking truck is just one of several Tesla models that have been delayed into next year.\nEngadget reports that according to the configuration page for the Tesla Cybertruck pickup, the vehicle will be delayed until next year. The company  informs potential customers that they will get to customize the truck when 'production nears in 2022.'\n\n\nWhile it was expected that single-motor Cybertruck's would tak",
      rights: 'breitbart.com',
      rank: 1459,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Lucas Nolan'],
      media: 'https://media.breitbart.com/media/2019/11/Elon-Musk-examines-cracked-Cybertruck-windows-640x335.jpg',
      is_opinion: false,
      twitter_account: '@lucasnolan',
      _score: 20.746288,
      _id: '11daeae0448d46759493c5f5e92a6398',
    },
    {
      title: "Bitcoin's price problems are unrelated to politics since 'Musk's tweets are more important.'",
      author: 'Helena Sutan',
      published_date: '2021-08-06 02:10:11',
      published_date_precision: 'full',
      link: 'https://en.brinkwire.com/finance/bitcoins-price-problems-are-unrelated-to-politics-since-musks-tweets-are-more-important/',
      clean_url: 'brinkwire.com',
      excerpt:
        "Bitcoin's price problems are unrelated to politics since 'Musk's tweets are more important.' BITCOIN has had a tumultuous 2021, with prices reaching new lows in June and July, but analysts say the…",
      summary:
        "Bitcoin's price problems are unrelated to politics since 'Musk's tweets are more important.'\nBITCOIN has had a tumultuous 2021, with prices reaching new lows in June and July, but analysts say the crypto's price issues are mainly due to volatility created by Twitter speculation generated by people like Elon Musk, rather than politics.\nBitcoin is currently trading at £27,680.11, down from a high of £46,212.41 in April. The sudden decline of the digital currency has been attributed to a number of ",
      rights: 'brinkwire.com',
      rank: 72979,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Helena Sutan'],
      media: 'https://en.brinkwire.com/nerede/uploads/2020/12/faviconV2.jpg',
      is_opinion: false,
      twitter_account: null,
      _score: 20.69427,
      _id: 'f1f717e3c236f526fce704bf471e320d',
    },
    {
      title: 'Elon Musk reveals his biography is underway; Walter Isaacson to work on the new book',
      author: 'Republic World',
      published_date: '2021-08-06 11:31:00',
      published_date_precision: 'full',
      link: 'https://www.republicworld.com/world-news/us-news/elon-musk-reveals-his-biography-is-underway-walter-isaacson-to-work-on-the-new-book.html',
      clean_url: 'republicworld.com',
      excerpt:
        "Tesla CEO Elon Musk revealed on August 5 on Twitter that apart from electric car maker and SpaceX's general news, Walter Isaacson is writing a biography.",
      summary:
        "Tesla CEO Elon Musk on August 5 2021, shared details about his new biography. He made this revelation through a tweet saying if anyone is 'curious' to know more about his ventures Tesla, SpaceX and general goings, can find it in his biography that'll be penned by Walter Isaacson. Isaacson's previous works include Leonardo da Vinci; Einstein: His Life and Universe, Kissinger: A Biography, Steve Jobs. Musk also said that Isaacson has shadowed him 'for several days so far' while adding that an auto",
      rights: 'republicworld.com',
      rank: 9700,
      topic: 'news',
      country: 'US',
      language: 'en',
      authors: ['Republic World'],
      media: 'https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/kd1u6oucctxxuufr_1628246413.jpeg',
      is_opinion: false,
      twitter_account: '@republic',
      _score: 20.641016,
      _id: 'f81815cf130648ed307431babd0faa16',
    },
    {
      title: "Why Bitcoin Doesn't Need a Leader — Not Even Elon Musk",
      author: 'Bitcoin News Editor',
      published_date: '2021-08-12 14:31:46',
      published_date_precision: 'full',
      link: 'https://forextv.com/bitcoin-news/why-bitcoin-doesnt-need-a-leader-not-even-elon-musk/',
      clean_url: 'forextv.com',
      excerpt:
        "However, I knew something those investors who only bought Bitcoin for quick return didn't: Bitcoin doesn't need a leader — not even Elon Musk. In fact, no one controls Bitcoin, and that's exactly what…",
      summary:
        "However, I knew something those investors who only bought Bitcoin for quick return didn't: Bitcoin doesn't need a leader — not even Elon Musk. In fact, no one controls Bitcoin, and that's exactly what …\nRead Full Story",
      rights: 'forextv.com',
      rank: 95968,
      topic: 'finance',
      country: 'US',
      language: 'en',
      authors: ['Bitcoin News Editor'],
      media: 'https://forextv.com/wp-content/uploads/2014/02/favicon.ico',
      is_opinion: false,
      twitter_account: null,
      _score: 20.589888,
      _id: '70d691194bf6235cecbc34b36cb42ef2',
    },
  ],
  user_input: {
    q: '"Elon Musk"',
    search_in: ['title', 'summary'],
    lang: ['en'],
    not_lang: null,
    countries: ['US', 'CA'],
    not_countries: null,
    from: '2021-08-06 00:00:00',
    to: null,
    ranked_only: 'True',
    from_rank: null,
    to_rank: null,
    sort_by: 'relevancy',
    page: 1,
    size: 50,
    sources: null,
    not_sources: null,
    topic: null,
    published_date_precision: null,
  },
}
